### ISSUE TITLE
can't import cloudsync

### ISSUE THREAD

**Issue by VirgileD** [AtakamaLLC/cloudsync#362]
Hello, I'm running arch, updated this morning.

I can't import cloudsync:
```
(venv) 14:06 virgiled@arcvi ~/Projects/lookout-radar/lookout > python
Python 3.9.0 (default, Jul 15 2021, 13:41:05) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudsync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/virgiled/Projects/lookout-radar/lookout/venv/lib/python3.9/site-packages/cloudsync/__init__.py", line 43, in <module>
    from .sync import *
  File "/home/virgiled/Projects/lookout-radar/lookout/venv/lib/python3.9/site-packages/cloudsync/sync/__init__.py", line 4, in <module>
    from .manager import *
  File "/home/virgiled/Projects/lookout-radar/lookout/venv/lib/python3.9/site-packages/cloudsync/sync/manager.py", line 24, in <module>
    from cloudsync.utils import debug_sig
  File "/home/virgiled/Projects/lookout-radar/lookout/venv/lib/python3.9/site-packages/cloudsync/utils.py", line 15, in <module>
    from _pytest.logging import PercentStyleMultiline
ModuleNotFoundError: No module named '_pytest'
```
Unfortunatly, from there I don't know what to do.
Can you help?

**Comment by earonesty** [comment]
hmm, apparently there's a problem with deps.   you can pip install pytest to pave over it for now, will fix soon

**Comment by earonesty** [comment]
https://github.com/AtakamaLLC/cloudsync/pull/364

**Comment by earonesty** [comment]
closing, that mr seems to fix
